### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by padraig** [comex/frash#1]
cp: /System/Library/Frameworks/IOSurface.framework/Versions/A/Headers: No such file or directory

**Comment by grp** [comment]
Snow Leopard required.

**Comment by iaminfinity** [comment]
/var/sdk/usr/include/stdarg.h:4:25: error: stdarg.h: No such file or directory What about that one?

**Comment by kangaroo** [comment]
Follow the README

**Comment by nhigh** [comment]
kangaroo, 
I tried your fork of frash but whenever I click on a flash object in safari it says "Could not connect: Connection refused"

**Comment by feisley** [comment]
nhigh,
The "install" script does not put the files in the proper location. You need to place the "food.plist" file in "/System/Library/LaunchDaemons/" and the food directory should be /var/mobile/frash/ not /var/root/frash

The connection refused message means that the "food" daemon is not running. Once you have the plist in the correct location and reboot the device, it should be running.

**Comment by cmoski** [comment]
feisley,

Thanks for your input. I am running into the same issue. The current installer script installs the files to /var/root/frash, so you are saying we should change that to /var/root/food as well as place food.plist in our launchdaemons directory?

Edit: Looks like the actual arguments are:
   <key>ProgramArguments</key>
    <array>
        <string>/var/mobile/frash/food_wrapper</string>
        <string>/var/mobile/frash/food</string>
        <string>inetd</string>
    </array>

So it needs to be in /var/mobile/frash..

**Comment by feisley** [comment]
Ooops my bad... its /var/mobile/frash and not /var/root/frash

If you change this line in the install script it will fix it:
rsync -avz food/food{,.sb,.plist,_wrapper} utils/lib{c,}utils.dylib icu/*.dylib  libflashplayer.so libgcc/libgccstuff.dylib oem.cfg root@ipad:/var/mobile/frash/

**Comment by nhigh** [comment]
My files are in /var/mobile/frash and I have placed the food.plist in /System/Library/LaunchDaemons but when I rebooted, it still did not work. I checked for the daemon using "launchctl list" and it was not there. Then I tried to load the daemon using "launchctl load /System/Library/LaunchDaemons/food.plist" and got this output "Bug: launchctl.c:2325 (23930):13: (dbfd = open(g_job_overrides_db_path, O_RDONLY | O_EXLOCK | O_CREAT, S_IRUSR | S_IWUSR)) != -1
launch_msg(): Socket is not connected"

**Comment by cmoski** [comment]
Just got it working.

My issue was that I took the iokit files from the OS and not the simulator. 

nhigh: When I run launchctl I get:

launchd% exit
Fluffy-Puff-III:~ root# launchctl load /System/Library/LaunchDaemons/food.plist
bind(): Address already in use
food: Already loaded

**Comment by feisley** [comment]
Yea, you shouldn't need to load it again if it loaded properly at boot.

**Comment by kangaroo** [comment]
Most of these issues are fixed on the tip of my branch (modulo the put the plist in the right place and load it step).  I'm heading to bed now, but I'll update the docs in the morning.  Bonus points if you send me a pull request with updated docs.
