### ISSUE TITLE
frash's big red flash placeholder is too big and too flashy

### ISSUE THREAD

**Issue by cadefra** [comex/frash#10]
the big read F logo is too visually disruptive. instead, it should blend more into the page. see ClickToFlash for a good example on how it should look:

http://clicktoflash.com/

**Comment by grp** [comment]
It's gone from the current comex version/fork/whatever-you-call-it because it's illegal to use that logo.

**Comment by ghost** [comment]
I am assuming you installed fresh with the .deb floating around the web, because this issue has already been taken care of, but the .deb file has not been updated to reflect the changes. The logo was copyrighted anyways.

**Comment by kangaroo** [comment]
Its gone from mine too.

**Comment by kangaroo** [comment]
In fact I never meant to push it, I meant to push a "g" owell; live and learn.

**Comment by darrenm01** [comment]
When I compile it now I get the gray background and the word "Flash" in a black font in the middle of the Flash area.

**Comment by imanono** [comment]
I love saurik

**Comment by CaptainN** [comment]
I doubt this is much more legal, but it was an idea:
http://www.unfocus.com/FrashIconConcept.png

Based off Grant Skinner's lego:
http://www.gskinner.com/blog/archives/2010/04/return_of_the_b.html
