### ISSUE TITLE
Build fails.

### ISSUE THREAD

**Issue by adozark** [comex/frash#12]
Everything went smoothly and I followed the instructions perfectly (or so I feel I did), yet the build fails. This is the output I get...

http://www.fileden.com/files/2010/7/13/2913794//BuildOutput.rtf
(It's much easier to read in this text file)

**Comment by grp** [comment]
Try putting your code somewhere else?

**Comment by adozark** [comment]
What do you mean? I've tried re cloning the source, using comex's source instead of kangaroos, I've uninstalled xcode and reinstalled it, (and tweaking the files again) and everything. I still can't get the xcodebuild to be successful.

**Comment by grp** [comment]
Clone it to somewhere else on your hard drive?

**Comment by adozark** [comment]
Yes. It still failed.

**Comment by kangaroo** [comment]
You havn't followed all of the instructions carefully and properly.

**Comment by adozark** [comment]
Ok I got it to build, Now I simply can't find "rsync" in cydia. Is it gone now?

**Comment by comex** [comment]
It's there.
