### ISSUE TITLE
Question about Frash.

### ISSUE THREAD

**Issue by NovaCool** [comex/frash#16]
I've been playing with my iPad (With the Flash) And I love it. Though I'm a little curious will ya'll have a flash for the iPod Touch?

**Comment by Qjz123** [comment]
Yes the frash 0.02 deb works on iPod touch 3G

**Comment by NovaCool** [comment]
No, I'm talking about about iPod touch 2G, right now I've noticed it has a dependency problem.

**Comment by Qjz123** [comment]
It will only work on the iPod touch 3G do to technical reasons the iPod touch 2g isn't powerful enough.

**Comment by zwaldowski** [comment]
It's not just a technical thing; the iPod touch 2G has the wrong CPU, a Cortex A7.  The device is essentially an iPhone 3G with souped-up graphics.

The iPhone 3G[s], iPad, iPod touch 3G, and iPhone 4 all have Cortex A8 variants (including the Apple A4 processor).  Cortex A8 processors use the heavily optimized armv7 processor architecture (earlier devices run armv6; newer support running these just like x86_64 processors can run i386 code).

Adobe requires (and, as such, their libflashplayer.so is compiled for) the armv7 architecture and will only run (at all, not just well) on a Cortex A8 or better.

**Comment by NovaCool** [comment]
Could you not switch the flash to armv6? And the libflashplayer does work. But right now I can only play Videos. (It allows me to play like a YouTube video.) It is possible, you might have bad quality flash though.

**Comment by comex** [comment]
Adobe could, I can't.  YouTube doesn't use frash.

**Comment by NovaCool** [comment]
No I'm saying when i manually install Flash 0.01-0.02. 

I'm not sure if you remember but, When you see YouTube in Desktop mode. There's that big clear Play Button.

That's what I see when I want to play a Flash Video. If you have iPod Touch 2G And you install the Frash. You'll see what I'm talking about exactly.
