### ISSUE TITLE
Does not work on Armv6 devices

### ISSUE THREAD

**Issue by rohinadalja** [comex/frash#20]
The build is not compiled to work on Armv6 devices yet

**Comment by GreySyntax** [comment]
The android flash library isn't armv6 compatible so it would be pointless.

**Comment by comex** [comment]
This.

**Comment by rohinadalja** [comment]
Thank you so much for replying. do you think it is possible to compile it for Armv6 devices? or is it not virtually possible, like according to the guy above you?

**Comment by comex** [comment]
It's possible, but it won't work.

**Comment by rohinadalja** [comment]
Thanks for the reply.. Id just like to thank you for all that you do in the scene.. and hope that frash would be compatible for old devices in the near future
