### ISSUE TITLE
_abort() classes.c:266

### ISSUE THREAD

**Issue by vcazan** [comex/frash#4]
Everything has been compiled and transfered to the iPad. When I try and load up any flash I get _abort() classes.c:266

Anyone know what this could be.

**Comment by kangaroo** [comment]
Read the README.  You need libflashplayer.so from beta1 which is the armeabi variant, the v7a variant is not supported yet.

**Comment by vcazan** [comment]
Realized I was using a bad version of libflashplayer.so, the one that works is 8.4MB the one I was using was only 7.4MB, might have been a beta or somthing

**Comment by feisley** [comment]
Just for historic note here:
Android Beta 1 is armeabi and works
Android Beta 2 and 3 are v7a and do not currently work.

**Comment by vcazan** [comment]
Also this might be the last cause, but if you turn JavaScript off flash will give you this error as well so make sure it is on

**Comment by kangaroo** [comment]
Fixed in my branch.
