### ISSUE TITLE
Signing failed (invalid)

### ISSUE THREAD

**Issue by sebs** [comex/frash#5]
warning: Application failed codesign verification.  The signature was invalid, or it was not signed with an Apple submission certificate. (-19011)
 Application failed codesign verification.  The signature was invalid, or it was not signed with an Apple submission certificate. (-19011)
failed to extract requirements data: 1
/Users/sschuermann/flashpad/frash/Player2/build/Release-iphoneos/Player2.app: code object is not signed
failed to extract entitlements: 1
- (null)

I anticipate this might be ok anyway?

**Comment by grp** [comment]
Yeah, probably, but you should use ldid instead of codesign.

**Comment by comex** [comment]
This-- follow the README
