### ISSUE TITLE
no such product type for the 'iphoneos' platform 

### ISSUE THREAD

**Issue by sebs** [comex/frash#6]
final build via xcode spills me the following ERROR

=== BUILD NATIVE TARGET Plugin OF PROJECT Player2 WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies
target specifies product type 'com.apple.product-type.library.dynamic', but there's no such product type for the 'iphoneos' platform
target specifies product type 'com.apple.product-type.library.dynamic', but there's no such product type for the 'iphoneos' platform
Internal error occurred while creating dependency graph: ASSERTION FAILURE in /SourceCache/DevToolsBase/DevToolsBase-1648/pbxcore/Target.subproj/PBXTargetBuildContext.m:2061
Details:  Assertion failed: [filePath isAbsolutePath]
Object:   PBXTargetBuildContext:0x114bfad80
Method:   -setHeadermapToolInvocation:forFilePath:
Thread:   <NSThread: 0x114c9c8f0>{name = (null), num = 3}
Backtrace:
  0  0x000000010030317f -[PBXTargetBuildContext(DependencyGraphEvents) handleFailureInMethod:object:fileName:lineNumber:messageFormat:arguments:](in DevToolsCore)
  1  0x000000010035fc1a _XCAssertionFailureHandler (in DevToolsCore)
  2  0x00000001002ff7d8 -[PBXTargetBuildContext setHeadermapToolInvocation:forFilePath:](in DevToolsCore)
  3  0x00000001001a1f23 -[XCCompilerSpecification computeDependenciesForFilePath:ofType:outputDirectory:inTargetBuildContext:](in DevToolsCore)
  4  0x0000000100417447 -[XCBuildRuleDGSnapshot(DependencyGraphCreation) computeDependenciesForFilePath:ofType:forBuildFileReference:withOutputDirectory:additionalProperties:inTargetBuildContext:](in DevToolsCore)
  5  0x00000001001a0987 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) _computeDependenciesForFilePath:ofType:forBuildFileReference:usingBuildRule:inTargetBuildContext:processedPaths:](in DevToolsCore)
  6  0x00000001001a0348 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForFilePath:ofType:forBuildFileReference:usingBuildRule:inTargetBuildContext:](in DevToolsCore)
  7  0x000000010019de72 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForBuildFileReference:inTargetBuildContext:](in DevToolsCore)
  8  0x000000010019d2eb -[XCBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesInTargetBuildContext:](in DevToolsCore)
  9  0x000000010019ce76 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesInTargetBuildContext:](in DevToolsCore)
 10  0x000000010019951d -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesInTargetBuildContext:](in DevToolsCore)
 11  0x000000010018b81f -[XCProductTypeSpecification computeDependenciesInTargetBuildContext:](in DevToolsCore)
 12  0x0000000100186a74 -[XCNativeTargetDGSnapshot(DependencyGraphCreation) computeDependenciesInTargetBuildContext:](in DevToolsCore)
 13  0x00000001001824d1 -[PBXTargetBuildContext createDependencyGraphWithTargetDGSnapshot:](in DevToolsCore)
 14  0x00000001001813d6 -[PBXTargetBuildContext(DependencyGraphEvents) dg_setTargetSnapshot:](in DevToolsCore)
 15  0x00007fff8470cd2c **invoking**_ (in CoreFoundation)
 16  0x00007fff8470cbfd -[NSInvocation invoke](in CoreFoundation)
 17  0x0000000100180d3f -[PBXTargetBuildContext(DependencyGraphEvents) processDependencyGraphEvents](in DevToolsCore)
 18  0x00007fff8470cd2c **invoking_** (in CoreFoundation)
 19  0x00007fff8470cbfd -[NSInvocation invoke](in CoreFoundation)
 20  0x00000001001808f7 -[XCInvocationQueue _processNextInvocationInThreadSlotNumber:](in DevToolsCore)
 21  0x0000000100180626 -[XCInvocationQueue _processInvocationsInThreadSlotNumber:](in DevToolsCore)
 22  0x00007fff88e07e8d **NSThread__main** (in Foundation)
 23  0x00007fff83357456 _pthread_start (in libSystem.B.dylib)
 24  0x00007fff83357309 thread_start (in libSystem.B.dylib)

Internal error occurred while creating dependency graph: ASSERTION FAILURE in /SourceCache/DevToolsBase/DevToolsBase-1648/pbxcore/Target.subproj/PBXTargetBuildContext.m:2061
Details:  Assertion failed: [filePath isAbsolutePath]
Object:   PBXTargetBuildContext:0x114bfad80
Method:   -setHeadermapToolInvocation:forFilePath:
Thread:   <NSThread: 0x114c9c8f0>{name = (null), num = 3}
Backtrace:
  0  0x000000010030317f -[PBXTargetBuildContext(DependencyGraphEvents) handleFailureInMethod:object:fileName:lineNumber:messageFormat:arguments:](in DevToolsCore)
  1  0x000000010035fc1a _XCAssertionFailureHandler (in DevToolsCore)
  2  0x00000001002ff7d8 -[PBXTargetBuildContext setHeadermapToolInvocation:forFilePath:](in DevToolsCore)
  3  0x00000001001a1f23 -[XCCompilerSpecification computeDependenciesForFilePath:ofType:outputDirectory:inTargetBuildContext:](in DevToolsCore)
  4  0x0000000100417447 -[XCBuildRuleDGSnapshot(DependencyGraphCreation) computeDependenciesForFilePath:ofType:forBuildFileReference:withOutputDirectory:additionalProperties:inTargetBuildContext:](in DevToolsCore)
  5  0x00000001001a0987 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) _computeDependenciesForFilePath:ofType:forBuildFileReference:usingBuildRule:inTargetBuildContext:processedPaths:](in DevToolsCore)
  6  0x00000001001a0348 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForFilePath:ofType:forBuildFileReference:usingBuildRule:inTargetBuildContext:](in DevToolsCore)
  7  0x000000010019de72 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForBuildFileReference:inTargetBuildContext:](in DevToolsCore)
  8  0x000000010019d2eb -[XCBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesInTargetBuildContext:](in DevToolsCore)
  9  0x000000010019ce76 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesInTargetBuildContext:](in DevToolsCore)
 10  0x000000010019951d -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesInTargetBuildContext:](in DevToolsCore)
 11  0x000000010018b81f -[XCProductTypeSpecification computeDependenciesInTargetBuildContext:](in DevToolsCore)
 12  0x0000000100186a74 -[XCNativeTargetDGSnapshot(DependencyGraphCreation) computeDependenciesInTargetBuildContext:](in DevToolsCore)
 13  0x00000001001824d1 -[PBXTargetBuildContext createDependencyGraphWithTargetDGSnapshot:](in DevToolsCore)
 14  0x00000001001813d6 -[PBXTargetBuildContext(DependencyGraphEvents) dg_setTargetSnapshot:](in DevToolsCore)
 15  0x00007fff8470cd2c **invoking**_ (in CoreFoundation)
 16  0x00007fff8470cbfd -[NSInvocation invoke](in CoreFoundation)
 17  0x0000000100180d3f -[PBXTargetBuildContext(DependencyGraphEvents) processDependencyGraphEvents](in DevToolsCore)
 18  0x00007fff8470cd2c **invoking_** (in CoreFoundation)
 19  0x00007fff8470cbfd -[NSInvocation invoke](in CoreFoundation)
 20  0x00000001001808f7 -[XCInvocationQueue _processNextInvocationInThreadSlotNumber:](in DevToolsCore)
 21  0x0000000100180626 -[XCInvocationQueue _processInvocationsInThreadSlotNumber:](in DevToolsCore)
 22  0x00007fff88e07e8d **NSThread__main** (in Foundation)
 23  0x00007fff83357456 _pthread_start (in libSystem.B.dylib)
 24  0x00007fff83357309 thread_start (in libSystem.B.dylib)
*\* BUILD FAILED **

**Comment by sebs** [comment]
This is just the change in 
http://sumgroup.wikispaces.com/iPhone_Dynamic_Library
missing ... the compile tells you that the dynamic libs are  not known to xcode, a thing you add with the stuff behind the url. I reinstalled xcode in the right version and hereby removed my changes ...

**Comment by grp** [comment]
Follow the directions.

**Comment by cmoski** [comment]
Added to wiki.

**Comment by sebs** [comment]
Thanks ;)
