### ISSUE TITLE
Build seems ok but signing seems not to work

### ISSUE THREAD

**Issue by sebs** [comex/frash#7]
The following build commands failed:
Player2:
    Ld /Users/sschuermann/flashpad/frash/Player2/build/Release-iphoneos/Player2.app/Player2 normal armv7
Plugin:
    CodeSign /Users/sschuermann/flashpad/frash/Player2/build/Release-iphoneos/Plugin.dylib
(2 failures)

on the end of teh xcode build

**Comment by grp** [comment]
Follow the directions, and use ldid instead of codesign.

**Comment by sebs** [comment]
Hmm, can you please get me a little more information on this. Maybe where i epicfailed to read the manual? This would be very kind of you. I will extend the wiki if needed.

**Comment by vcazan** [comment]
After you have downloaded the archive, unpack the files and put them into /usr/local/bin directory. Then make sure they are both executable. Then you can use the terminal commands.

**Comment by sebs** [comment]
flynn:bin sschuermann$ ls -lsa ldid*
64 -rwxr-xr-x@ 1 sschuermann  admin  32016  7 Jul 01:04 ldid
 8 -rwxr-xr-x  1 sschuermann  admin    437  7 Jul 01:04 ldid2

**Comment by sebs** [comment]
flynn:bin sschuermann$ pwd
/usr/local/bin
